# Generated by Django 4.1.5 on 2023-09-11 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_post_delete_postlike'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='PostLikes',
        ),
    ]
