# Generated by Django 4.1.5 on 2023-09-12 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_rename_postlikes_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
