# Generated by Django 4.1.5 on 2023-09-23 15:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0018_remove_newpost_likes_newpost_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newpost',
            name='likes',
        ),
        migrations.AddField(
            model_name='newpost',
            name='likes',
            field=models.ManyToManyField(blank=True, default=0, related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
