# Generated by Django 4.1.5 on 2023-09-24 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0020_remove_newpost_likes_newpost_likes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostLike',
            new_name='Like',
        ),
    ]
